"""empty message

Revision ID: 044af8cdc1e3
Revises: 7b69b45dbf12
Create Date: 2025-07-31 19:06:20.776154

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '044af8cdc1e3'
down_revision: str | Sequence[str] | None = '7b69b45dbf12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('nodes', 'title')
    op.drop_column('nodes', 'content')
    op.drop_column('nodes', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nodes', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nodes', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('nodes', 'data')
    # ### end Alembic commands ###
