"""empty message

Revision ID: 1502e70d658b
Revises: 93eda93c5abb
Create Date: 2025-07-29 18:40:10.869692

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1502e70d658b'
down_revision: str | Sequence[str] | None = '93eda93c5abb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('position_x', sa.Integer(), nullable=False))
    op.add_column('nodes', sa.Column('position_y', sa.Integer(), nullable=False))
    op.drop_column('nodes', 'x')
    op.drop_column('nodes', 'updated_at')
    op.drop_column('nodes', 'created_at')
    op.drop_column('nodes', 'y')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('nodes', 'position_y')
    op.drop_column('nodes', 'position_x')
    # ### end Alembic commands ###
