"""empty message

Revision ID: 52f5cdabe30e
Revises: 5e442c05c8ec
Create Date: 2025-08-13 18:50:42.850747

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.modules.roadmap.domain.edge.value_objects import EdgeType

# revision identifiers, used by Alembic.
revision: str = '52f5cdabe30e'
down_revision: str | Sequence[str] | None = '5e442c05c8ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    edge_type_enum = sa.Enum(EdgeType, name='edgetype')
    edge_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('edges', sa.Column('type', edge_type_enum, server_default=EdgeType.BEZIER.name, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'type')
    # ### end Alembic commands ###
