"""empty message

Revision ID: 7b69b45dbf12
Revises: 1502e70d658b
Create Date: 2025-07-29 19:21:26.584764

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '7b69b45dbf12'
down_revision: str | Sequence[str] | None = '1502e70d658b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
